version: '3.8'
services:
  db:
    image: mysql:8.0-debian
    ports:
      - 9001:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Qwe123!@#
      - MYSQL_DATABASE=database
      - MYSQL_USER=krystian
      - MYSQL_PASSWORD=krystian123

  phpmyadmin:
    image: phpmyadmin:5.2.1
    links:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=krystian
      - PMA_PASSWORD=krystian123

  php:
    build:
      ./docker/php
    volumes:
      - .:/var/www/krystian:delegated
    links:
      - db

  nginx:
    image: nginx:1.19
    ports:
      - 8010:80
    volumes:
      - .:/var/www/krystian:delegated
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php